server:
  port: 8088

spring:
  application:
    name: test
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
      
zk: 127.0.0.1:2181