apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-centos
  name: nginx-centos-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-centos
  type: ClusterIP
