apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-centos-deployment
spec:
  selector:
    matchLabels:
      app: nginx-centos
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-centos
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        volumeMounts:
        - name: html-dir
          mountPath: /usr/share/nginx/html
      - name: centos
        image: centos:centos7.4.1708
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: html-dir
          mountPath: /root/cxixt
      volumes:
      - name: html-dir
        emptyDir: {}
