# image: oracle-jdk1.8.0_77
# descr: 提供纯净的oracle jre8，位置：/opt/jdk1.8.0_77

FROM centos

MAINTAINER caixt, xiantong0216@126.com


ADD jdk-linux-x64-1.8.77.tar.gz /opt

ENV JAVA_HOME /opt/jdk1.8.0_77
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk1.8.0_77/bin