spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    check: false
    timeout: 30000
    address: multicast://224.5.6.7:1234
    #address: 127.0.0.1:2181
    #client: curator
    #protocol: zookeeper
  protocol:
    # 指定通信协议
    name: dubbo
    # 通信端口，这里指的是与消费者间的通信协议与端口
    port: 8888
    threadpool: cached
    threads: 200
    serialization: hessian2
  provider:
    timeout: 30000
    retries: 0
  consumer:
    retries: 0
    check: false
    timeout: 30000
    loadbalance: leastactive
